export const CONTRACTS = {
  ENTRY_POINT: '0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789',
  SMART_ACCOUNT_FACTORY: process.env.VITE_SMART_ACCOUNT_FACTORY || '',
  VERIFYING_PAYMASTER: process.env.VITE_VERIFYING_PAYMASTER || '',
  SESSION_KEY_MODULE: process.env.VITE_SESSION_KEY_MODULE || '',
  RECOVERY_MODULE: process.env.VITE_RECOVERY_MODULE || '',
} as const