# .github/workflows/deploy.yml
name: Deploy to Base Sepolia

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-contracts:
    runs-on: ubuntu-latest
    environment: testnet
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        cd contracts && npm ci

    - name: Create .env file
      run: |
        echo "ALCHEMY_API_KEY=${{ secrets.ALCHEMY_API_KEY }}" >> .env
        echo "PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}" >> .env
        echo "ETHERSCAN_API_KEY=${{ secrets.ETHERSCAN_API_KEY }}" >> .env
        echo "BASE_SEPOLIA_RPC_URL=https://base-sepolia.g.alchemy.com/v2/${{ secrets.ALCHEMY_API_KEY }}" >> .env
        echo "ENTRYPOINT_ADDRESS=0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789" >> .env

    - name: Compile contracts
      run: cd contracts && npm run compile

    - name: Deploy to Base Sepolia
      run: cd contracts && npm run deploy:base-sepolia

    - name: Verify contracts
      run: cd contracts && npm run verify:base-sepolia

    - name: Save deployment addresses
      uses: actions/upload-artifact@v3
      with:
        name: deployment-addresses
        path: contracts/deployments/

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: [deploy-contracts]
    environment: production
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        cd frontend && npm ci

    - name: Download deployment addresses
      uses: actions/download-artifact@v3
      with:
        name: deployment-addresses
        path: contracts/deployments/

    - name: Create frontend .env
      run: |
        echo "VITE_ALCHEMY_API_KEY=${{ secrets.ALCHEMY_API_KEY }}" >> frontend/.env
        echo "VITE_WALLETCONNECT_PROJECT_ID=${{ secrets.WALLETCONNECT_PROJECT_ID }}" >> frontend/.env
        echo "VITE_CHAIN_ID=84532" >> frontend/.env

    - name: Build frontend
      run: cd frontend && npm run build

    - name: Deploy to Vercel
      uses: vercel/action@v1
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: frontend